import "../styles/index.scss";
import Header from "./components/header/Header";
import { Secular_One, Roboto, Poppins } from "next/font/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const secular = Secular_One({
    subsets: ["latin"],
    weight: "400",
});
const roboto = Roboto({
    subsets: ["latin"],
    weight: ["400", "700"],
});
const font = Poppins({
    subsets: ["latin"],
    weight: ["100", "400", "700"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="no">
            <body className={font.className}>
                <div id="backdrop"></div>
                <div id="modal"></div>

                <main>{children}</main>
            </body>
        </html>
    );
}
