import "../styles/index.scss"
import Header from "./components/header/Header"
import { Secular_One } from "@next/font/google"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const secular = Secular_One({
  subsets: ["latin"],
  weight: '400'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={secular.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
